### ISSUE TITLE
Loading progress bar

### ISSUE THREAD

**Issue by lightningorb** [AIObjectives/talk-to-the-city-reports#105]
Some very significant speedups are currently being pushed out, that'll result in reports loading in a handful of seconds. However since load times are strongly correlated with bounce rate, an aesthetically pleasing progress bar with potentially relevant information (such as filenames that are being loaded) could help retain the user whilst the report is loading.

**Comment by colleenm** [comment]
I think Shyal sped up load time enough that this is pretty low priority now, assigning P3 accordingly
