### ISSUE TITLE
Add explanatory text to TttC report generation UI

### ISSUE THREAD

**Issue by colleenm** [AIObjectives/talk-to-the-city-reports#108]
(follow up to issue in previous repo)

I've added UI text to add to the "number of reports to be processed" node in the UI text master doc: https://docs.google.com/document/d/1jGvGjODJq-B5df3iJHMzb8GazlJSvqiLqGbGsMOczs0/edit#heading=h.tmux3ahr4qg

This text is written with the assumption that this field is empty by default when a report is first created (currently the default value is 2). I think this more intuitive for the default use case and we are more likely to surprise users by processing limited rows.

I'll continue to use this bug for updates to the report generation UI to maintain context, but it's fine to close the bug when each new change is complete.

**Comment by lightningorb** [comment]
Done.
