### ISSUE TITLE
Header UI updates

### ISSUE THREAD

**Issue by colleenm** [AIObjectives/talk-to-the-city-reports#118]
New header design:

![header](https://github.com/AIObjectives/talk-to-the-city-reports/assets/1048995/8710ae96-2641-49b6-93d4-1f3db254033e)

Header should remain fixed to the top of the page.

Functionality is as before, things are just moved around and look different.

For now, logged-in users should just see a hamburger menu instead of the "sign in" button. In the future we'll likely want to move the items in that menu elsewhere in the UI but that can be done as a follow up.

![header logged in](https://github.com/AIObjectives/talk-to-the-city-reports/assets/1048995/6b3afbea-a8b5-4f39-9d69-8654c629c77a)

Any white github logo is fine.

**Comment by lightningorb** [comment]
Done.
