### ISSUE TITLE
Add per-topic graphs of subtopics

### ISSUE THREAD

**Issue by colleenm** [AIObjectives/talk-to-the-city-reports#124]
Each topic should have a bar graph showing a list of subtopics, their descriptions, and the number of claims in each subtopic.

The styling of these graphs should be identical to the styling of the graph at the top of the page, with one exception: all bars representing subtopics should be the same color, and should be the color that represents their parent topic in the graph at the top of the page.

The graphs should be placed below the topic description, and above the first subtopic heading:

![Uploading whole page UI changes.png…]()

**Comment by lightningorb** [comment]
![image](https://github.com/AIObjectives/talk-to-the-city-reports/assets/24770400/160bbf49-559a-44a5-a3b5-a5465cd3cab5)

**Comment by lightningorb** [comment]
Estimate: 3 hours

**Comment by lightningorb** [comment]
It seems we're left aligning now?

![image](https://github.com/AIObjectives/talk-to-the-city-reports/assets/24770400/bcd65344-a895-4b12-83b1-55ae4579f9b5)

I guess i'll stick with roughly 800 pixels, and left align.
