### ISSUE TITLE
Add report name to the tab title

### ISSUE THREAD

**Issue by theboldzoey** [AIObjectives/talk-to-the-city-reports#136]
title : Talk to the City - {report-name}

<img width="1027" alt="image" src="https://github.com/AIObjectives/talk-to-the-city-reports/assets/53463832/386dd0eb-ee95-4dad-860e-a1bcaa7223b3">

**Comment by lightningorb** [comment]
I went with `{report-name}` directly (without Talk to the City) as this provides more information. When the user has many tabs open, the width of the tab does not accommodate the entire width of "Talk to the City - {report-name}".

I'm hoping @colleenm can create a better looking favicon than i did, to make the tab easily recognizable.

Let me know if that's OK. If not, feel free to re-open this issue.

**Comment by lightningorb** [comment]
Update: use slug instead

**Comment by colleenm** [comment]
LGTM. I'll file a separate bug for the favicon.

@theboldzoey if this looks good to you I think this issue can be closed

**Comment by theboldzoey** [comment]
LGTM!
