### ISSUE TITLE
Preserve user-entered whitespace in report description

### ISSUE THREAD

**Issue by brittneygallagher** [AIObjectives/talk-to-the-city-reports#141]
**Describe the bug**
Hitting Enter in the description field is not preserved

**To Reproduce**
1. Open https://tttc-turbo.web.app/report/heal-michigan-edit-claims
2. Hover text to the report title and click the pencil to edit
3. In the description hit enter after "(referred to below as “returning citizens”).

**Expected behavior**
Text after moves to a new row

**Actual behavior**
Enter is not preserved

**Comment by lightningorb** [comment]
Done.
