### ISSUE TITLE
Remove "Forked From" for anon viewer

### ISSUE THREAD

**Issue by brittneygallagher** [AIObjectives/talk-to-the-city-reports#145]
**Describe the bug**
Forked From display for all users, this should only be applicable for the reporter.

**To Reproduce**
1. Go to https://tttc-turbo.web.app/report/heal-michigan-edit-claims

**Expected behavior**
There is no Forked from.

**Actual behavior**
Forked from: heal-michigan

**Comment by lightningorb** [comment]
Done.
