### ISSUE TITLE
example.csv was broken when downloading repo as zip file.

### ISSUE THREAD

**Issue by tomy7912348** [AIObjectives/talk-to-the-city-reports#15]
when downloading repo as zip file,
the content of example.csv would be replace as this:

```
version https://git-lfs.github.com/spec/v1
oid sha256:c30db8ce360aa13fe7bcf943d0c3213f2b492a38c9ef897158b0dafe068e5be9
size 58446
```

**Comment by Onurbon** [comment]
Thanks for spotting this!  

The csv files are stored using git lfs so you probably need to install this: https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage. 

I also updated the README.
