### ISSUE TITLE
Left navigation & report order don't match top bar graph

### ISSUE THREAD

**Issue by colleenm** [AIObjectives/talk-to-the-city-reports#153]
**Describe the bug**
There's a mismatch between the bar graph at the top of a report (which is ordered correctly) and the order of topics in the report body and left navigation column.

**To Reproduce**
1. Start new project
2. Upload this CSV: 
[AI Workshop Survey Responses - 8 responses - ideal futures only (2).csv](https://github.com/AIObjectives/talk-to-the-city-reports/files/14414484/AI.Workshop.Survey.Responses.-.8.responses.-.ideal.futures.only.2.csv)
3. Use prompts from this report: https://tttc-turbo.web.app/report/ai-ideal-futures-workshop-survey-1/
4. Scroll to main report bar graph

**Expected behavior**
The bar graph, report, and left navigation list show topics in the same order

**Actual behavior**
The bar graph and the left navigation list show topics in a different order; the bar graph is correctly sorted by claims per topic, but the left navigation pane and the report body show a different (random?) order.

**Screenshots**
![Screen Shot 2024-02-26 at 20 48 08](https://github.com/AIObjectives/talk-to-the-city-reports/assets/1048995/69b1083b-62dd-4dbb-844c-ce1451e83ed6)

**Additional Context**

**Comment by lightningorb** [comment]
Fixed.
