### ISSUE TITLE
Generate Report displays for non-logged in user

### ISSUE THREAD

**Issue by brittneygallagher** [AIObjectives/talk-to-the-city-reports#156]
**Describe the bug**

**To Reproduce**
1. Go to https://tttc-turbo.web.app/report/heal-michigan-edit-claims

**Expected behavior**
Generate Report does not display

**Actual behavior**
Generate report displays.

**Screenshots**
<img width="1383" alt="image" src="https://github.com/AIObjectives/talk-to-the-city-reports/assets/11606773/5ab04575-8254-40bb-ae3e-ca22fc16435c">

**Comment by lightningorb** [comment]
Done.
