### ISSUE TITLE
Firefox only: hover on Claims blinks really fast

### ISSUE THREAD

**Issue by brittneygallagher** [AIObjectives/talk-to-the-city-reports#157]
**Describe the bug**
Hovering on claims is hard to look at 

**To Reproduce**
1. Open https://tttc-turbo.web.app/report/heal-michigan-edit-claims using Firefox
2. Hover over Reentry Challenges

**Expected behavior**
Hover behaves like it does in Brave/Chrome

**Actual behavior**
It's blinky and really hard to look at 

**Screenshots**

**Comment by lightningorb** [comment]
Fixed.
