### ISSUE TITLE
Chat doesn't display answers after first question

### ISSUE THREAD

**Issue by brittneygallagher** [AIObjectives/talk-to-the-city-reports#165]
**Describe the bug**
As a non-logged in user trying to use chat - the response to a second question does not display

**To Reproduce**
1. Click on project '(https://talktothecity.org/report/heal-michigan-chat) - use private browsing
2. Add Open AI Key
3. Add Pinecone secret key
4. Click Generate
5. Ask a question, like what are some challenges for returning citizens?
6. Wait for answer
7. Ask another question, like what technology issues did returning citizens have?

**Expected behavior**
The chat answer displays

**Actual behavior**
The answer does not display if you open the Console, you can see that the response is there - it just doesn't display

**Comment by lightningorb** [comment]
Fixed with PR: https://github.com/AIObjectives/talk-to-the-city-reports/pull/151
