### ISSUE TITLE
Pipeline failed to build final report in conda enviroment

### ISSUE THREAD

**Issue by tomy7912348** [AIObjectives/talk-to-the-city-reports#17]
Trying to run the pipeline on conda enviroment with Ubuntu22.04 in python = 3.11.5. When running pipeline with example file and local data, it manages to generate numerous files output folder, but failed to generate final report.

[args.csv](https://github.com/AIObjectives/talk-to-the-city-reports/files/13227354/args.csv)
[clusters.csv](https://github.com/AIObjectives/talk-to-the-city-reports/files/13227355/clusters.csv)
[labels.csv](https://github.com/AIObjectives/talk-to-the-city-reports/files/13227356/labels.csv)
[overview.txt](https://github.com/AIObjectives/talk-to-the-city-reports/files/13227357/overview.txt)
[result.json](https://github.com/AIObjectives/talk-to-the-city-reports/files/13227358/result.json)
[status.json](https://github.com/AIObjectives/talk-to-the-city-reports/files/13227359/status.json)
[takeaways.csv](https://github.com/AIObjectives/talk-to-the-city-reports/files/13227360/takeaways.csv)
[translations.json](https://github.com/AIObjectives/talk-to-the-city-reports/files/13227362/translations.json)

**Comment by Onurbon** [comment]
Duplicate from #16 ?

**Comment by tomy7912348** [comment]
I tought its a different problem, but its also fixed after updating node.js to v21. Thanks!
