### ISSUE TITLE
Add switch to set report to Private/Public

### ISSUE THREAD

**Issue by brittneygallagher** [AIObjectives/talk-to-the-city-reports#181]
Currently once a report is created it's available to anyone. There should be an option in 'Additional Settings' that makes the report only visible to the creator of the dataset. Ideally this would be a switch with Private on the left and Public on the right. Default to Private.

<img width="155" alt="2024-04-16_00-11-48" src="https://github.com/AIObjectives/talk-to-the-city-reports/assets/11606773/353eb32c-ed9e-4f94-966f-f8a4ecbfcf03">

**Comment by lightningorb** [comment]
Done.

**Comment by brittneygallagher** [comment]
I only see it when I add a new report - is it there for existing ones?

**Comment by brittneygallagher** [comment]
I didn't see my comment post to the channel, so I re-opened for clarification: I only see it when I add a new report - is it there for existing ones? There is a scenario where you want to change the visibility at some point so this should be something that can be done at any time.

**Comment by lightningorb** [comment]
![image](https://github.com/AIObjectives/talk-to-the-city-reports/assets/24770400/af4f701c-1c44-458f-a5b6-9ebf043dc7f3)
![image](https://github.com/AIObjectives/talk-to-the-city-reports/assets/24770400/e7c6db49-5921-4225-b0f1-21ae990295eb)
