### ISSUE TITLE
Traditional Chinese UI request

### ISSUE THREAD

**Issue by theboldzoey** [AIObjectives/talk-to-the-city-reports#27]
moda is asking for an UI with Traditional Chinese. 
@mashbean and I can help with the translation. @lightningorb please let us know which html file is the correct one for the current UI. thanks!

**Comment by lightningorb** [comment]
Traditional chinese should be in the UI if your web browser is configured to zh-TW

https://gtranslate.io/detect-browser-language

Could you let me know what browser local folks are using?

**Comment by lightningorb** [comment]
Closing as this is now done. UI fully translated to traditional Taiwanese Mandarin.
