### ISSUE TITLE
Ability to flag an argument as incorrect

### ISSUE THREAD

**Issue by lightningorb** [AIObjectives/talk-to-the-city-reports#42]
Issue by @brittneygallagher:

**Repro steps**

1. open https://tttc-turbo.web.app/report/heal-michigan-7
2. Click on Community Support > Family & Social Networks > Victims of domestic violence lack sufficient safe avenues to seek help.

**Expected behavior**
Non-logged in user: 
- Add ability to flag a claim as inaccurate (Claim should be capitalized)
- claim is removed from the section in the report as well
- For now this is any user who can do this

Logged in user: All that the non-logged in user can see as well as view this list of removed claims. This should include the following:
- Category
- Subcategory
- Claim
- Participant

**Actual behavior**
There is no way to hide a claim and remove it from the report.

**Screenshots**
![image](https://github.com/AIObjectives/tttc-turbo/assets/11606773/b5d5db03-caea-4184-b84f-161690d8c4e6)

Here's where the thumbs down came from: https://fontawesome.com/icons/thumbs-down?f=classic&s=regular

**Additional context**
This is v1 of a greater feature. It is needed for HM, so participants can flag any content they disagree with. More broadly we will have to consider what this looks like as we get more traction. Who should be able to disagree and we likely in future should add clarification.

**Comment by lightningorb** [comment]
![image](https://github.com/AIObjectives/talk-to-the-city-reports/assets/24770400/64b4f4ea-40d8-4d13-af44-4d13d396072e)

This feature is currently in progress via the "Feedback" node. Currently flagging a claim as not belonging to the dataset will hide it on next load.

**Comment by brittneygallagher** [comment]
This works.

**Comment by brittneygallagher** [comment]
This works.
