### ISSUE TITLE
Design (still in progress)

### ISSUE THREAD

**Issue by lightningorb** [AIObjectives/talk-to-the-city-reports#43]
Issue by @brittneygallagher:

- [x] Use [NextUI](https://nextui.org/docs/components) where possible
- [x] Use [Font Awesome](https://fontawesome.com/download) use free for web for icons
- [x] Use Google fonts: 
        Headings/Titles - [Quattrocento](https://fonts.google.com/specimen/Quattrocento) 
        Body - [Quattrocento Sans](https://fonts.google.com/specimen/Quattrocento+Sans) 
- [ ] Color Palette for text: https://colorhunt.co/palette/053b50176b8764ccc5eeeeee
       Body text would be the dark blue #053B50
       Titles would be the not as dark blue #176B87
       Highlights/emphasis color would be the mint #64CCC5
       Background color would be the grey #EEEEEE
- ~[ ] Color palette for circles: https://coolors.co/palette/001219-005f73-0a9396-94d2bd-e9d8a6-ee9b00-ca6702-bb3e03-ae2012-9b2226 (background would be the grey already used)~

**Comment by brittneygallagher** [comment]
Discussed today and agreed that the circles color palette is a bit too varied. Will re-visit.

**Comment by colleenm** [comment]
Superceded by other design bugs given new UI, resolving
