### ISSUE TITLE
Bug: report generation fails when "Number of rows to be processed" is blank

### ISSUE THREAD

**Issue by colleenm** [AIObjectives/talk-to-the-city-reports#58]
Steps to reproduce:
1. create new report with arbitrary title/url/description
2. choose "heal michigan" template in advanced features
3. upload [this CSV](url) of heal michigan interviews
4. delete the number '2' from the "Number of rows to be processed" field
5. click "Generate Report"

Expected behavior: report is generated
Observed behavior: nothing happens (no toasts or anything)

My understanding was that this field should be left blank to include all rows of data, which I think is better UX than requiring the user to specify the exact number of rows they have.

I saw this suspiciously text-field-related console error that might be relevant
![Screen Shot 2024-01-03 at 13 36 58](https://github.com/AIObjectives/talk-to-the-city-reports/assets/1048995/fa8a9a2b-1d92-4995-b411-30ec5595f975)

**Comment by colleenm** [comment]
If I'm right in that understanding (about leaving the field blank to include all rows), we should also add text guidance to that effect. I'll add that to bug #35 once Shyal confirms that's the expected behavior

**Comment by brittneygallagher** [comment]
I believe the value should be 129 (# of rows in the csv) in the "Number of
rows to be processed" - unless that changed

**Comment by colleenm** [comment]
@brittneygallagher are you saying the intended behavior should be to require users to input the number of rows in their CSV? I disagree, I think it shouldn't be too technically challenging to calculate that for them

**Comment by brittneygallagher** [comment]
I don't think that's how it should be, but that's how it is right now. I
just wanted to let you know what you need to do to get the report working
right now.

**Comment by lightningorb** [comment]
It makes perfect sense of an empty value to not filter, and let all the data pass through.

**Comment by lightningorb** [comment]
Done.
