### ISSUE TITLE
Add video to pop-up when clicking on a representative argument

### ISSUE THREAD

**Issue by brittneygallagher** [AIObjectives/talk-to-the-city-reports#59]
**Repro steps**

1. Go to https://tttc-turbo.web.app/report/heal-michigan-7-adjusted-backup-final (or any report with video)
2. Under Employment Barriers, click "Returning citizens from affluent backgrounds may have..."
3. The Quote pop-up opens

**Expected behavior**
The video should display under Interview

**Actual behavior**
Only the quote and interview name are displayed.

**Comment by brittneygallagher** [comment]
To match from the circles, the video would be after "Interview", but I propose we change that in both places and have the order be:

Claim (if present)
Quote
Video
Interview

@colleenm leaving this greater change out in case you have other ideas

**Comment by colleenm** [comment]
no strong opinions, I like having the person's name above the video but fine either way

**Comment by brittneygallagher** [comment]
We will leave as it

**Comment by lightningorb** [comment]
Fixed in PR #62 .
