### ISSUE TITLE
When filtered by participant, Feedback > I think this claim is miscategorized > Topic and Subtopic options are also filtered by participant

### ISSUE THREAD

**Issue by brittneygallagher** [AIObjectives/talk-to-the-city-reports#66]
**Repro steps**

1. Open https://tttc-turbo.web.app/report/heal-michigan-7-adjusted-backup
2. Filter by Clarence Price
3. Click any claim
4. Click "!" for feedback, check the first checkbox, "I think the claim is miscategorized"
5. Click "Topic"

**Expected behavior**
The list of all Topics displays. 

**Actual behavior**
The list of Topics displays, but also includes "other"
<img width="414" alt="image" src="https://github.com/AIObjectives/talk-to-the-city-reports/assets/11606773/de32460a-26d4-4d04-a18b-c45852b9881d">

6. Select "Systemic Issues"
7. Click "Subtopic"

**Expected behavior**
The list of all Subtopics under Systemic Issues displays (Prison gerrymandering, resource allocation, legislative barriers, voting rights)

**Actual behavior**
Only Resource Allocation dislpays (that's all that Clarence was in)

**Screenshots**
Add screenshots *if* they help explain your problem.

**Comment by lightningorb** [comment]
Fixed.
