### ISSUE TITLE
Video disappears after clicking play when clicking on a representative argument in the report view 

### ISSUE THREAD

**Issue by brittneygallagher** [AIObjectives/talk-to-the-city-reports#71]
**Repro steps**

1. Open https://tttc-turbo.web.app/report/heal-michigan
2. Scroll down to the report 
3. Click any Representative Argument
4. Play the video

**Expected behavior**
The popup remains and the video plays

**Actual behavior**
For me, the popup closes, but you can hear the video. For Cozine he did not hear the video.

**Comment by lightningorb** [comment]
Confirmed.

**Comment by lightningorb** [comment]
Fixed.

**Comment by brittneygallagher** [comment]
One thing I noticed is now the popup is under the claim and not off to the side. Doesn't need to be fixed for my review tomorrow, but probably should be fixed. 

<img width="759" alt="image" src="https://github.com/AIObjectives/talk-to-the-city-reports/assets/11606773/147f0950-ee87-4ecc-95f9-a9e1a23c6e95">
