### ISSUE TITLE
Move language picker to the header bar

### ISSUE THREAD

**Issue by colleenm** [AIObjectives/talk-to-the-city-reports#73]
The language picker isn't discoverable when viewing a report, since it's at the bottom of the page. Users who don't generate reports are unlikely to have seen our UI before and so won't know to look there for the language menu.

Moving the language picker to the top-right part of the header is consistent with where it's placed on other sites:
<img width="1105" alt="Screen Shot 2024-01-08 at 12 19 08" src="https://github.com/AIObjectives/talk-to-the-city-reports/assets/1048995/db832705-c0f0-442b-9b87-23e123df3659">

Making the language picker overall slightly smaller, and making the flag icon bigger, would help this fit in the header while also being noticeable enough for first-time users. The screenshot above shows ideal spacing and sizing.

**Comment by lightningorb** [comment]
Done.
