### ISSUE TITLE
Add "Appendix" section to end of report to show code/prompts used to generate clusters

### ISSUE THREAD

**Issue by colleenm** [AIObjectives/talk-to-the-city-reports#75]
The old TttC report-only UI (currently at tttc.dev) included an "Appendix" section that let viewers see the code and prompts used for each step of the pipeline:

<img width="757" alt="Screen Shot 2024-01-09 at 10 46 03" src="https://github.com/AIObjectives/talk-to-the-city-reports/assets/1048995/625d2e25-cc12-4c9f-8963-623a24606601">

I think including this info fits with the spirit of TttC being an open-source project, and I'd like to add it back to the new UI, as a final section under all the other clusters.

The UI used previously is good: naming each step with links/buttons to show the code and prompts, with a separate note about manual changes.

If we can reuse the old code for this somehow, it's fine to drop this into the new UI unstyled while we work on overall style changes.

**Comment by lightningorb** [comment]
Definitely doable.

**Comment by lightningorb** [comment]
![image](https://github.com/AIObjectives/talk-to-the-city-reports/assets/24770400/eb0a027a-f35c-4245-a439-50f0533cfbb6)

![image](https://github.com/AIObjectives/talk-to-the-city-reports/assets/24770400/744f4537-c974-4ccb-accb-177c3216cd09)

![image](https://github.com/AIObjectives/talk-to-the-city-reports/assets/24770400/d83d4165-3dbd-4f7b-9c89-edc2287718aa)

**Comment by colleenm** [comment]
@lightningorb this is awesome, thanks for the screenshots. I LOVE the syntax highlighting in the code view

Two nits:
1. The steps need human-readable names, e.g. the titles of each step in the report generation UI, and I think having more punctuation would be helpful. We don't need to show nodes where not much happens on the backend (e.g. openai key). How about:

1. [whatever jq_v1_1 is, what is this?
2. Cluster extraction: [show code](#), [show code](#) ([model name])
3. Argument extraction: [show code](#), [show code](#) ([model name])
4. Incorporate feedback: [show code](#)
5. Sort arguments into clusters: [show code](#)
6. Generate report: [show code](#)

(note: the title for (4) might be wrong if I'm wrong about what we're doing with the merge node)

2. I'm generally not in favor of modal content unless we're trying to block the user from accessing other parts of the UI; for viewing the prompts/code here, I think viewing them inline is better (e.g. use case: someone wants to flip back and forth between looking at a prompt and looking at some of the claims that resulted). Is it possible to have this view inline, and just expand it (and push later steps below) when the user clicks "show code" (or "show prompt")?

There are arguments for putting the code in a modal, but I think consistency between prompt+code views is more important.

**Comment by lightningorb** [comment]
@colleenm 

Update. Will keep on refining.

![image](https://github.com/AIObjectives/talk-to-the-city-reports/assets/24770400/55b5cf9d-f970-403e-9c8e-c59008592e7b)

![image](https://github.com/AIObjectives/talk-to-the-city-reports/assets/24770400/c836a84e-a06b-4fd5-95f1-5db7df64b334)

![image](https://github.com/AIObjectives/talk-to-the-city-reports/assets/24770400/74d8881b-2c76-435e-b8b1-db2ecbc4bf15)

**Comment by lightningorb** [comment]
> [whatever jq_v1_1 is, what is this?

[JQ](https://en.wikipedia.org/wiki/Jq_(programming_language) manipulates JSON. By connecting a JQ node right after the CSV node, we are able to transform any CSV file into our internal format, for example.

**Comment by lightningorb** [comment]
I've filtered out the open ai key. If you'd like more descriptive texts, we'll need to do them for all the nodes, in all languages. If so, feel free to re-open this ticket.

Closing.
