### ISSUE TITLE
Small style changes for report view bubble chart

### ISSUE THREAD

**Issue by colleenm** [AIObjectives/talk-to-the-city-reports#76]
These are interim improvements while I work out what our final UI should be. @lightningorb if any of these start to get complicated, skip for now and let me know

* [x] 1. Remove white outline from around all text (text should remain black)
* [x] 2. Change circle background color scheme to use colors light enough to support non-outlined black text
* [x] 3. Use font optimized for small text. I recommend [Inter](https://fonts.google.com/specimen/Inter). ([Noto sans](https://fonts.google.com/noto/specimen/Noto+Sans) is a fine alternative but let's try Inter)
* [x] 4. Remove gray circle bounding the topic bubbles (or make it transparent)
* [x] 5. Slightly increase padding between circles. See screenshot below

Notes:
2) color scheme: use this color palette, ideally in this order (left to right) so that reports generally use more of the left-most colors. All these colors give black text a >7:1 contrast ratio, meeting accessibility standards for small text
![tttc color palette](https://github.com/AIObjectives/talk-to-the-city-reports/assets/1048995/2b291017-72c0-4c3c-a579-63338c92d259)

5) padding between circles: the padding between all the green/teal circles is about right in this image (padding around "success stories" is very slightly too much, artifact of me hacking this in the dev console):
<img width="482" alt="Screen Shot 2024-01-09 at 12 48 33" src="https://github.com/AIObjectives/talk-to-the-city-reports/assets/1048995/cdd5ba0e-f0e9-44e1-8489-416955f847b2">

**Comment by lightningorb** [comment]
Done.
