### ISSUE TITLE
Report generation: error toasts should never disappear

### ISSUE THREAD

**Issue by colleenm** [AIObjectives/talk-to-the-city-reports#80]
Steps to reproduce:
- create new report
- do something wrong (I actually still don't know what I did wrong)
- click "generate report"

Expected behavior:
- Many toast notifications describing progress appear and disappear in the right column
- If there are any toasts describing errors, those toasts remain visible (pinned to top of column) until the user clicks the X on them to close them

Observed behavior:
- a red error text flashes briefly and then disappears before I can read it full

**Comment by lightningorb** [comment]
I'll close this, as errors now go in the logs that are readily available in the UI.
