### ISSUE TITLE
Make finding recent reports easier on the homepage

### ISSUE THREAD

**Issue by colleenm** [AIObjectives/talk-to-the-city-reports#82]
The current list of reports is ordered alphabetically, without timestamps on each report item.

A better UI would include timestamps on the reports, and possibly order by recency.

Assigning to self for design spec, will update description with spec.

**Comment by lightningorb** [comment]
I've sorted by recency for now, as that doesn't require design input. Definitely much much better.

**Comment by lightningorb** [comment]
We could even check this in, and you could file another report if you feel the need for timestamps.

**Comment by colleenm** [comment]
Ordering by recency is fine for now, thanks! Fine to close this without adding timestamps when recency sorting is live, I'll do a full UX pass on homepage at some point

**Comment by lightningorb** [comment]
Done.
