### ISSUE TITLE
Update pipeline to handle surveys with multiple questions and responses

### ISSUE THREAD

**Issue by colleenm** [AIObjectives/talk-to-the-city-reports#85]
(Assigning to self for deciding product questions)

Right now, the pipeline expects a CSV with a single "comment-body" value for each row/respondent. As a result, we can only accept datasets that have all participant responses in one CSV column. This requires more effort from users, many of whom may not be familiar with the excel formulas necessary to merge CSV columns easily.

Fixing this requires solving two issues:

1. How do we handle an indefinite number of content columns?

Likely solution:
- Require a few specifically named columns (comment-id, interview), and then process all additional column values the way we process "comment-body" values (i.e. as respondent's own words): requires user understanding but minimal user effort, and allows users to easily upload CSVs with a bunch of irrelevant columns (e.g. timestamps -- this is relevant for nontechnical users uploading google sheets data from a google form)
- 
Alternative:
- Require all content columns to be prepended with a specific string (e.g. "content-"), and process only those columns as responses: requires minimal user understanding, but users have to delete columns

2. How do we handle yes/no or multiple-choice questions?

If most of the semantic content of a response is in a question posed, that content won't be present in the values for that question's column. This can be solved by rewriting all these values as statements that include the content of both the question and answer -- but that may be complicated for nontechnical users, and also may be difficult to automate. As of now, it also generates a lot of duplicate claims.

Possible solutions:
- Require users to upload CSVs where all content column values are statements, as though they are participants' own words; update the pipeline to merge duplicate claims. Puts the burden on users, but ensures that data is processed by someone familiar with its context (i.e. the reporter user)
- Add a separate pipeline step to process yes/no or multiple-choice questions in a specific way, and require such columns to be specifically named. Seems overcomplicated for the value we'd get.
- ???

**Comment by lightningorb** [comment]
> but users have to delete columns

You don't have to delete columns. You can absolutely have unused columns. I don't recommend it as it'll make loading the pipeline slower. But it certainly won't break things.

**Comment by colleenm** [comment]
@lightningorb example of what I'm talking about:

a survey includes a multi-choice question like "May we contact you in the future for follow up questions?" where each choice is a full sentence (e.g. "Please do not contact me in the future about my responses to this survey"), but the content is irrelevant to what the rest of the survey investigates.

In this case, if we treat all non-specifically-labeled columns as relevant, we might generate a topic bubble about people's preferences about future contact, and the report creator may not want that.

But this needs more thinking through in general, I think the other solution (prepending column titles with "content-") may work better
