### ISSUE TITLE
Latency Optimization Task: Node-18

### ISSUE THREAD

**Issue by lightningorb** [AIObjectives/talk-to-the-city-reports#99]
We are experiencing unexpected latency spikes in Node 18 for LLM related functionality. These spikes are intermittently affecting performance, leading to slower report generation.

https://docs.google.com/document/d/1T7uHdH0hT6JJHthmJO94eh3vg5F1RuC1ch_LyhCnM0M/edit

**Comment by colleenm** [comment]
@lightningorb I thought this got fixed -- are all the issues here resolved?

**Comment by lightningorb** [comment]
Yes indeed.
